const ethnicityToFlag: Record<string, string> = {
  Afghan: "🇦🇫",
  African: "🌍",
  "African American": "🇺🇸",
  Albanian: "🇦🇱",
  Algerian: "🇩🇿",
  American: "🇺🇸",
  Andorran: "🇦🇩",
  Angolan: "🇦🇴",
  "Antiguan and Barbudan": "🇦🇬",
  Argentine: "🇦🇷",
  Armenian: "🇦🇲",
  Australian: "🇦🇺",
  Austrian: "🇦🇹",
  Azerbaijani: "🇦🇿",
  Bahamian: "🇧🇸",
  Bahraini: "🇧🇭",
  Bangladeshi: "🇧🇩",
  Barbadian: "🇧🇧",
  Belarusian: "🇧🇾",
  Belgian: "🇧🇪",
  Belizean: "🇧🇿",
  Beninese: "🇧🇯",
  Bhutanese: "🇧🇹",
  Bolivian: "🇧🇴",
  Bosnian: "🇧🇦",
  Botswanan: "🇧🇼",
  Brazilian: "🇧🇷",
  British: "🇬🇧",
  Bruneian: "🇧🇳",
  Bulgarian: "🇧🇬",
  Burkinabe: "🇧🇫",
  Burundian: "🇧🇮",
  Caucasian: "🏳️",
  Cambodian: "🇰🇭",
  Cameroonian: "🇨🇲",
  Canadian: "🇨🇦",
  "Cape Verdean": "🇨🇻",
  "Central African": "🇨🇫",
  Chadian: "🇹🇩",
  Chilean: "🇨🇱",
  Chinese: "🇨🇳",
  Colombian: "🇨🇴",
  Comorian: "🇰🇲",
  Congolese: "🇨🇬",
  "Costa Rican": "🇨🇷",
  Croatian: "🇭🇷",
  Cuban: "🇨🇺",
  Cypriot: "🇨🇾",
  Czech: "🇨🇿",
  Danish: "🇩🇰",
  Djiboutian: "🇩🇯",
  Dominican: "🇩🇴",
  Dutch: "🇳🇱",
  "East Timorese": "🇹🇱",
  Ecuadorian: "🇪🇨",
  Egyptian: "🇪🇬",
  Emirati: "🇦🇪",
  "Equatorial Guinean": "🇬🇶",
  Eritrean: "🇪🇷",
  Estonian: "🇪🇪",
  Ethiopian: "🇪🇹",
  Fijian: "🇫🇯",
  Finnish: "🇫🇮",
  French: "🇫🇷",
  Gabonese: "🇬🇦",
  Gambian: "🇬🇲",
  Georgian: "🇬🇪",
  German: "🇩🇪",
  Ghanaian: "🇬🇭",
  Greek: "🇬🇷",
  Grenadian: "🇬🇩",
  Guatemalan: "🇬🇹",
  Guinean: "🇬🇳",
  "Guinea-Bissauan": "🇬🇼",
  Guyanese: "🇬🇾",
  Haitian: "🇭🇹",
  Honduran: "🇭🇳",
  Hungarian: "🇭🇺",
  Icelandic: "🇮🇸",
  Indian: "🇮🇳",
  Indonesian: "🇮🇩",
  Iranian: "🇮🇷",
  Iraqi: "🇮🇶",
  Irish: "🇮🇪",
  Israeli: "🇮🇱",
  Italian: "🇮🇹",
  Ivorian: "🇨🇮",
  Jamaican: "🇯🇲",
  Japanese: "🇯🇵",
  Jordanian: "🇯🇴",
  Kazakhstani: "🇰🇿",
  Kenyan: "🇰🇪",
  Kiribati: "🇰🇮",
  Kuwaiti: "🇰🇼",
  Kyrgyz: "🇰🇬",
  Laotian: "🇱🇦",
  Latvian: "🇱🇻",
  Lebanese: "🇱🇧",
  Lesotho: "🇱🇸",
  Liberian: "🇱🇷",
  Libyan: "🇱🇾",
  Liechtenstein: "🇱🇮",
  Lithuanian: "🇱🇹",
  Luxembourger: "🇱🇺",
  Macedonian: "🇲🇰",
  Malagasy: "🇲🇬",
  Malawian: "🇲🇼",
  Malaysian: "🇲🇾",
  Maldivian: "🇲🇻",
  Malian: "🇲🇱",
  Maltese: "🇲🇹",
  Marshallese: "🇲🇭",
  Mauritanian: "🇲🇷",
  Mauritian: "🇲🇺",
  Mexican: "🇲🇽",
  Micronesian: "🇫🇲",
  Moldovan: "🇲🇩",
  Monegasque: "🇲🇨",
  Mongolian: "🇲🇳",
  Montenegrin: "🇲🇪",
  Moroccan: "🇲🇦",
  Mozambican: "🇲🇿",
  Namibian: "🇳🇦",
  Nauruan: "🇳🇷",
  Nepalese: "🇳🇵",
  "New Zealander": "🇳🇿",
  Nicaraguan: "🇳🇮",
  Nigerian: "🇳🇬",
  Nigerien: "🇳🇪",
  "North Korean": "🇰🇵",
  Norwegian: "🇳🇴",
  Omani: "🇴🇲",
  Pakistani: "🇵🇰",
  Palauan: "🇵🇼",
  Palestinian: "🇵🇸",
  Panamanian: "🇵🇦",
  "Papua New Guinean": "🇵🇬",
  Paraguayan: "🇵🇾",
  Peruvian: "🇵🇪",
  Polish: "🇵🇱",
  Portuguese: "🇵🇹",
  Qatari: "🇶🇦",
  Romanian: "🇷🇴",
  Russian: "🇷🇺",
  Rwandan: "🇷🇼",
  "Saint Kitts and Nevis": "🇰🇳",
  "Saint Lucian": "🇱🇨",
  "Saint Vincentian": "🇻🇨",
  Samoan: "🇼🇸",
  "San Marinese": "🇸🇲",
  "Sao Tomean": "🇸🇹",
  "Saudi Arabian": "🇸🇦",
  Senegalese: "🇸🇳",
  Serbian: "🇷🇸",
  Seychellois: "🇸🇨",
  "Sierra Leonean": "🇸🇱",
  Singaporean: "🇸🇬",
  Slovak: "🇸🇰",
  Slovenian: "🇸🇮",
  "Solomon Islander": "🇸🇧",
  Somali: "🇸🇴",
  "South African": "🇿🇦",
  "South Korean": "🇰🇷",
  "South Sudanese": "🇸🇸",
  Spanish: "🇪🇸",
  "Sri Lankan": "🇱🇰",
  Sudanese: "🇸🇩",
  Surinamese: "🇸🇷",
  Swazi: "🇸🇿",
  Swedish: "🇸🇪",
  Swiss: "🇨🇭",
  Syrian: "🇸🇾",
  Taiwanese: "🇹🇼",
  Tajik: "🇹🇯",
  Tanzanian: "🇹🇿",
  Thai: "🇹🇭",
  Togolese: "🇹🇬",
  Tongan: "🇹🇴",
  "Trinidadian and Tobagonian": "🇹🇹",
  Tunisian: "🇹🇳",
  Turkish: "🇹🇷",
  Turkmen: "🇹🇲",
  Tuvaluan: "🇹🇻",
  Ugandan: "🇺🇬",
  Ukrainian: "🇺🇦",
  Uruguayan: "🇺🇾",
  Uzbek: "🇺🇿",
  Vanuatuan: "🇻🇺",
  Venezuelan: "🇻🇪",
  Vietnamese: "🇻🇳",
  Yemeni: "🇾🇪",
  Zambian: "🇿🇲",
  Zimbabwean: "🇿🇼",
};

const getFlagForEthnicity = (ethnicity: string): string => {
  return ethnicityToFlag[ethnicity] || "🌍";
};

export default getFlagForEthnicity;
